### ISSUE TITLE
口上のエラーメッセージ

### ISSUE THREAD

**Issue by NoxHeolstor** [erablue-resort/erablue_resort#69]
ディスコードうまく使えないのでこっちに失礼しました。
まずはクオリティー高いです！めっちゃハマりました！

バグか私のパソコンの原因かわかりませんが、
特殊口上ありのキャラに話しかけると（会話やお茶を淹れるなど）

` 
口上_キャラ個別ERB\EVENT_KOJO.ERBの109行目でエラーが発生しました:Emuera1824+v18+EMv17+EEv45
	TRYCALLFORM KOJO_COM_{NO:TARGET}_{SELECTCOM}(TARGET)
エラー内容：KOJO_COM_1_300関数: 引数が多すぎます
現在の関数：@KOJO_MESSAGE_COM（口上_キャラ個別ERB\EVENT_KOJO.ERBの5行目）
関数呼び出しスタック：
SOURCE.ERBの194行目（関数@SOURCE_CHECK内）
TRAIN_MAIN.ERBの33行目（関数@TRAIN_MAIN_LOOP内）
TRAIN_MAIN.ERBの55行目（関数@TRAIN_MAIN内）
起床前メニュー関連処理\起床前メニュー.ERBの151行目（関数@USERSHOP内）`

このようなエラーコードが出てきます・・・一旦キャラ個別口上のフォルダーを削除したら遊べますが原因がわかりません(´；ω；`)
お手数ですがどうか対応お願いします。

**Comment by erablue-resort** [comment]
あっ、すいませんここの存在に気づかず放置しちゃってました！
報告ありがとうございます！！
該当のバグについては、口上テンプレートの更新に伴うバグでして、現在は治っているので本体を更新してもらえれば大丈夫だと思います！
またプレイよろしくお願いします！
